package GUI;

import Model.Originator;
import Model.Position;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class MementoPattern extends javax.swing.JFrame {

    private final Originator originator;

   
    public MementoPattern() {
        initComponents();
        setTitle("Golf Ball Tracker");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icon/golfball.png")));
        setLocationRelativeTo(null);
        ground_lbl.setLayout(null);
        golf_ball_lbl.setVisible(false);
        originator = new Originator();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        undo_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        golf_ball_lbl = new javax.swing.JLabel();
        ground_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        undo_button.setBackground(new java.awt.Color(153, 255, 153));
        undo_button.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        undo_button.setForeground(new java.awt.Color(255, 255, 255));
        undo_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-undo-50.png"))); // NOI18N
        undo_button.setText("UNDO");
        undo_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undo_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(undo_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 0, -1, -1));

        golf_ball_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/golfball.png"))); // NOI18N
        jPanel1.add(golf_ball_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, 38));

        ground_lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ground_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/view-top-golf-course-vector.jpg"))); // NOI18N
        ground_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ground_lblMouseClicked(evt);
            }
        });
        jPanel1.add(ground_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered

    }//GEN-LAST:event_jPanel2MouseEntered

    private void ground_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ground_lblMouseClicked
        try {
            int x = evt.getX();
            int y = evt.getY();
            Location(x, y);
            originator.setPosition(new Position(x, y));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ground_lblMouseClicked

    private void undo_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undo_buttonActionPerformed
        try {
            originator.undo();
            if (originator.getPosition() != null) {
                Location(originator.getPosition().getX(), originator.getPosition().getY());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_undo_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MementoPattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MementoPattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MementoPattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MementoPattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MementoPattern().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel golf_ball_lbl;
    private javax.swing.JLabel ground_lbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton undo_button;
    // End of variables declaration//GEN-END:variables

    
    
    
    public void Location(int x, int y) {
        try {
            golf_ball_lbl.setVisible(true);
            Dimension dimensionsize = golf_ball_lbl.getPreferredSize();
            golf_ball_lbl.setBounds((x - dimensionsize.width / 2), (y - dimensionsize.height), dimensionsize.width, dimensionsize.height);
            ground_lbl.add(golf_ball_lbl);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
